# Generated by Django 5.2.1 on 2025-06-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_userhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='tool_url',
            field=models.CharField(blank=True, help_text='URL инструмента, с которым связано действие', max_length=200, null=True),
        ),
    ]
